### ISSUE TITLE
unit_of_measurement for weekIncidence

### ISSUE THREAD

**Issue by hajo62** [thebino/rki_covid#10]
A unit for the WeekIncidence would be nice to have the option to diplay graphs or history.
<img width="366" alt="grafik" src="https://user-images.githubusercontent.com/15800980/104429807-5087fc80-5586-11eb-82a4-be7d1e46ab39.png">

Maybe you could provide an example for configuration.yaml to be able to add a unit of measurement.

**Comment by thebino** [comment]
You can use the built-in line graph to add it to lovelace: https://github.com/thebino/rki_covid#graph

Or you can create a trend sensor to use it in automations: https://github.com/thebino/rki_covid#automations

**Comment by hajo62** [comment]
Is it possible to configure in `configuration.yaml` instead of gui?

**Comment by thebino** [comment]
The lovelace is separated from any component, so AFAIK it is not possible to add it to the configuration file.
Also when adding a new card, lovelace will showcase the count already.
![Screenshot 2021-01-13 at 14 37 21](https://user-images.githubusercontent.com/841681/104459469-0e25e600-55ad-11eb-94e0-120482fcdf6d.png)

Country wide numbers can be added by the [Coronavirus Integration](https://www.home-assistant.io/integrations/coronavirus/)

**Comment by hajo62** [comment]
Maybe I was not clear enough explaining my idea.
I there is no unit of measure, the history (the old one shown above in my screenshot) shows no graph, but descrete values. If a sensor has a unit, it show like your other values: 
<img width="400" alt="grafik" src="https://user-images.githubusercontent.com/15800980/104460487-745f3880-55ae-11eb-9530-444386710906.png">
Yes, the graph is another option to display; but with a maybe small change, the history would work, too.

Regarding configuration: I was talking about the `sensor:` section in the file `configuration.yaml` to configure a sensor and not the lovelace configuration to i.e. configure a card. If I could configure your integration here, I easily could add a unit of measure by my self. (And yes, I know that this number does not have a _unit_, but HA expects one to display in the old history.)

Country wide numbers: Yes, but... Those numbers are from Johns Hopkins University and I would love to have German offical numbers from RKI.

**Comment by thebino** [comment]
Ah, now I got it. You recommend to change the unit_of_measure for incidence.
This was already [discussed earlier](https://github.com/thebino/rki_covid/issues/5#issuecomment-751462860)
Since `incidence` is more like a proportion or rate, I will not change the unit. Also HA will change its behaviour based on this unit.
