### ISSUE TITLE
API unreachable

### ISSUE THREAD

**Issue by ipd-otto** [thebino/rki_covid#18]
Integration can't get any API answer for a few days now. After the latest update to v0.3.0 I checked the log:

```
Logger: custom_components.rki_covid
Source: helpers/update_coordinator.py:166
Integration: RKI Covid numbers (documentation, issues)
First occurred: 12:21:32 (1 occurrences)
Last logged: 12:21:32

Error fetching rki_covid data: Error communicating with API: Cannot connect to host api.corona-zahlen.org:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1125)')]
```

Seems as if the used API does not provide valid certificates.

**Comment by oli737** [comment]
2021-01-17 14:47:55 ERROR (MainThread) [custom_components.rki_covid] Error fetching rki_covid data: Error communicating with API: Cannot connect to host api.corona-zahlen.org:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1125)')]

Same here.

**Comment by bcutter** [comment]
Copy that.

`Error fetching rki_covid data: Error communicating with API: Cannot connect to host api.corona-zahlen.org:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1125)')] `

Discovered this when upgrading to v0.3.0.

**When will the certificate(s) be fixed?** Don´t want to workaround by tweaking to "allow self-signed certificates" or disabling full ssl validity check.

**Comment by oli737** [comment]
> Copy that.
> 
> `Error fetching rki_covid data: Error communicating with API: Cannot connect to host api.corona-zahlen.org:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1125)')] `
> 
> Discovered this when upgrading to v0.3.0.
> 
> **When will the certificate(s) be fixed?** Don´t want to workaround by tweaking to "allow self-signed certificates" or disabling full ssl validity check.

It seams the sever is down and not the certificate is broken. Atleast I think that.

**Comment by bcutter** [comment]
Too bad, wanted to add the new entities provided with 0.3.0 update. Hopefully it will be fixed soon... by the way there´ve been some outages already the days before, but I can´t provide logs for those. Anyway, current messages are quite clear.

**Comment by oli737** [comment]
> Too bad, wanted to add the new entities provided with 0.3.0 update. Hopefully it will be fixed soon... by the way there´ve been some outages already the days before, but I can´t provide logs for those. Anyway, current messages are quite clear.

Same here. I waiting setup version 0.3 too.

**Comment by LuckyTriple7** [comment]
API is now up and working.

**Comment by thebino** [comment]
API is up and running again. Sorry for the outage, hopefully the RKI system will now stay online.
