### ISSUE TITLE
Overall numbers as sensor

### ISSUE THREAD

**Issue by pytz** [thebino/rki_covid#19]
First of all thanks for the very useful integration!

I have a question: is it possible to add sensors on the country (=whole Germany) or state (=North Rhine-Westphalia) level?  
Based on the district data it should be possible to sum up the numbers.

**Comment by thebino** [comment]
There is an Integration for country wide numbers: https://www.home-assistant.io/integrations/coronavirus/

For state wide numbers, feel free to create a pull request ;)
