### ISSUE TITLE
Add more then one LK at a time?

### ISSUE THREAD

**Issue by ph0b0s101** [thebino/rki_covid#20]
Hello and thank you for your really nice Integration. The only real thing I am missing is the possiblity to add more then one LK at a time. Would be nice to find the feature in the near future.

**Comment by thebino** [comment]
Just add another integration of the same type and select a different District.

`Configurations > Integrations > Add new Integration`

<img width="947" alt="Screenshot 2021-01-26 at 12 41 52" src="https://user-images.githubusercontent.com/841681/105840794-dfa80200-5fd3-11eb-815c-7bebaa3958f1.png">

**Comment by ph0b0s101** [comment]
Omg, this was easy. Sorry i did not know that this is possible. Thank you very much :-D
