### ISSUE TITLE
district - Where to get valid values

### ISSUE THREAD

**Issue by Hooch76** [thebino/rki_covid#23]
The title already contains all I wanna know: Where to get valid values for district?

Edit: i haven't installed it yet but after re-reading the Readme it seems as it is done by  configuring the integration with the GUI and not editing configuration.yml,

Thanks

**Comment by thebino** [comment]
Hi, thanks for your feedback. I just updated the configuration instructions in the readme.
It is possible to add new integrations via the user interface or the configuration.yaml

I hope, the new instructions are more easily comprehensible now.
https://github.com/thebino/rki_covid#configuration
