### ISSUE TITLE
Request failed <ClientResponse(https://api.corona-zahlen.org/districts) [502 Bad Gateway]

### ISSUE THREAD

**Issue by LuckyTriple7** [thebino/rki_covid#25]
Logger: custom_components.rki_covid.api
Source: custom_components/rki_covid/api.py:171
Integration: RKI Covid numbers (documentation, issues)
First occurred: 6:58:21 (1 occurrences)
Last logged: 6:58:21

Request failed <ClientResponse(https://api.corona-zahlen.org/districts) [502 Bad Gateway]> <CIMultiDictProxy('Server': 'nginx/1.19.3', 'Date': 'Fri, 12 Feb 2021 05:58:21 GMT', 'Content-Type': 'text/html', 'Content-Length': '157', 'Connection': 'keep-alive', 'Strict-Transport-Security': 'max-age=31536000')>

**Comment by LuckyTriple7** [comment]
A few hours later it worked again

**Comment by Whippie72** [comment]
For me the same. I reinstalled the integration over HACS. Works :)

**Comment by rolandsteinmeyer** [comment]
Still have the error.

**Comment by thebino** [comment]
The backend should already be back online again: https://github.com/marlon360/rki-covid-api/issues/92
