### ISSUE TITLE
Cant find integration after HACS install

### ISSUE THREAD

**Issue by FcBayern3** [thebino/rki_covid#29]
No integration found in integrations after installing over HACS.

**Comment by thebino** [comment]
Have you restarted the system? If so, please try to add a sensor manually;
https://github.com/thebino/rki_covid#configuration

**Comment by FabiThe1** [comment]
Tried the install without Hacs, but after the restart the System goes into safe mode, because the configuration.yaml can't find the integration for the sensor data.

**Comment by arifroni** [comment]
same for me, i tried to add the sensors manually, but get an error....integration not found.

**Comment by thebino** [comment]
Can you share the rki_covid part of your configuration so I can have look.
The integration hasn't changed since a month but I don't want to preclude an error in it.

**Comment by FabiThe1** [comment]
i got it yesterday with hacs. Did 20 restarts then it was working.

**Comment by Progaros** [comment]
**ctr + f5** in the browser did it for me (after the restart)

**Comment by JoachimEngelmann** [comment]
You need to clear your browser cache after installing an integration in HACS and then you can find in in Configuration->Integrations. Alternativly use another browser or browser configuration, if you don't want to clear your whole cache. That is what i have done right now

**Comment by thebino** [comment]
As @JoachimEngelmann already pointed out, it is recommended to clear the browser cache after _installing_ an integration for the first time: https://hacs.xyz/docs/categories/integrations/#special-notes-about-integrations
