### ISSUE TITLE
Do you want me to add GitHub actions?

### ISSUE THREAD

**Issue by KTibow** [thebino/rki_covid#3]
If you want, I can add some advanced CI to your repo in a PR. Let me know if you want that.
- Do you want to enable auto-formatting?
- Do you want packaged or independent (I recommend packaged because I can send updates)?

**Comment by thebino** [comment]
Feel free to add actions and packaging. I thought a release step should be sufficient.

**Comment by KTibow** [comment]
Thanks! Mind answering some of the questions in the bullet points?

**Comment by thebino** [comment]
@KTibow If it improves the quality of the project, feel free to create a PR.
There are already workflows for code formatting / styling.
