### ISSUE TITLE
Inzidenz for whole Germany

### ISSUE THREAD

**Issue by tenenteandrea** [thebino/rki_covid#30]
first of all thanks for the great work! I really like it.
My isn't an issue but more a questions. 
I see in the latest changelog that  you wrote:
     Added state sensors and whole germany

How can I add a sensor for "whole Germany" (Inzidenz, New cases ....)?
Thanks for your help.

**Comment by thebino** [comment]
There is a "district" called "Deutschland"
Sorry for the inconvenience since it isn't a translated string.

<img width="405" alt="germany" src="https://user-images.githubusercontent.com/841681/111495391-9ce6e880-873f-11eb-80f7-2ac11682ca63.png">

**Comment by tenenteandrea** [comment]
Perfect! Thank you so much!
