### ISSUE TITLE
Missing manifest file

### ISSUE THREAD

**Issue by pytz** [thebino/rki_covid#32]
Recognized a warning today:

> WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for  custom integration 'rki_covid'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'rki_covid'

Any custom component is required to have a manifest.json in the future:
https://developers.home-assistant.io/docs/creating_integration_manifest/

Added to home assistant within this pull request: https://github.com/home-assistant/core/pull/45919

**Comment by thebino** [comment]
The version key was already added back in February. Please update to the latest version.
