### ISSUE TITLE
Der Konfigurationsfluss konnte nicht geladen werden

### ISSUE THREAD

**Issue by Dog6574** [thebino/rki_covid#36]
Hi. 

I get this error message after installation the hacs integration, reboot and  I try to install the rki integration.

Gtrx.
Dog

**Comment by lennartgrunau** [comment]
Getting the same issue on Version 1.5.0.
Core Version `core-2021.4.5`.

Could configure successfully via `configuration.yaml`, so it's just the ui config that's broken.

**Comment by thebino** [comment]
Thanks for pointing out. Just released [a bugfix version 1.5.1](https://github.com/thebino/rki_covid/releases/tag/1.5.0).
