### ISSUE TITLE
Sensor sensor.NAME_weekIncidence is not saved to the influxDB

### ISSUE THREAD

**Issue by vaceslav** [thebino/rki_covid#41]
Hello,

First, thank you for so one great integration!!!

In my installation I configured influxDB to log all data.
The configuration looks like this one.

`  influxdb:  
      host: 172.20.0.101`

All sensors except one are logged:
![image](https://user-images.githubusercontent.com/24871/115990936-4a161180-a5c6-11eb-9158-91db4e65b4c7.png)

So the sensor **NAME_weekIncidence**  is missing

**Comment by thebino** [comment]
Whats the purpose of the InfluxDB? HA already persists all values internally, just wondering why someone would install a separate persistence layer.

I can only guess, but you can try to change the `unit_of_measurement` to get the value persisted.
https://github.com/thebino/rki_covid/blob/master/custom_components/rki_covid/sensor.py#L169

This looks like an issue on the influx configuration, all external values should be escaped to prevent XSS attacks to the database.

**Comment by vaceslav** [comment]
The purpose to use InfluxDB is to save sensor data over the years and the possibility to query the data in milliseconds.
I tried to update my InfluxDB installation from version 1.x to 2.x but it seems to be a little bit complicated. I will try to update my installation on the weekend. 
I let you know if it changed something.

**Comment by AgentP38** [comment]
I have also installed a influx dB and the same issue.

If you change the unit_of_measurement in the customize.yaml you will find the week incidence in influxdb.

Hope that helps.

**Comment by dabepp** [comment]
> If you change the unit_of_measurement in the customize.yaml you will find the week incidence in influxdb.

In the configuration.yaml or customize.yaml (Which I can't find)?

**Comment by vaceslav** [comment]
You have to change it in [customize.yaml](https://www.home-assistant.io/docs/configuration/customizing-devices/)

@thebino can you change the unit in your awesome integration?  
Because not every user will change it in customize.yaml but want to use InfluxDB

**Comment by AgentP38** [comment]
@vaceslav Yes correct...

@dabepp please have a look to homeassistant spec...

https://www.home-assistant.io/docs/configuration/customizing-devices/

Maybe that helps.

@thebino I also think that a change the unit of  measurement shall be changed...

It is small hole in a very big implementation of your integration. Where a lot of guys have fun with...

**Comment by thebino** [comment]
To which value did you change it? The sensor is representing an **incidence number**.

**Comment by AgentP38** [comment]
I just represent with number nb

**Comment by vaceslav** [comment]
I changed it to **cases**. Yes not the best choice I now. 
I think InfluxDB has problem with **#** sign.
