### ISSUE TITLE
vaccination data

### ISSUE THREAD

**Issue by mampfes** [thebino/rki_covid#42]
First of all: Thanks for this great integration :-)

I wonder if it would be possible to also add the vaccination quotes. I don't know if they are provided by the RKI directly, but they are available in tab-separated files on https://impfdashboard.de/

What I've found out so far: There are several .tsv files, which include a magic hex code in the file name. I add the names I found today (25-04-2021). I don't know so far if the file names are static or change dynamically.

https://impfdashboard.de/data/regions.4593ee96.tsv
Contains list of all "Bundesländer" and population count (required to calculate vaccination quote).

https://impfdashboard.de/data/germany_vaccinations_by_state.c473dafa.tsv
Contains vaccination count, including first and full vaccination count per Bundesland.

With this 2 files, it would be possible to calculate all vaccination numbers for Germany and all Bundesländer.

So it would be great if you could add these numbers.

**Comment by thebino** [comment]
There are two issues with these data:

 1. the data aren't reliable according to the RKI since the data is tracked decentralized.
    source: https://www.rki.de/DE/Content/Infekt/Impfen/Impfstatus/impfstatus_node.html

 2. the rki provided by rki are xlsx based and need to be parsed
    source: https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Impfquoten-Tab.html
    xlsx: https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Impfquotenmonitoring.xlsx?__blob=publicationFile

But with the provided links, it should be possible to add a parsing to the [rki-covid-parser](https://github.com/thebino/rki-covid-parser/)

**Comment by mampfes** [comment]
Ok, great. Don't hesitate to contact me if you need help. I have some experience with web scrapers in Python.

**Comment by thebino** [comment]
@mampfes no web scraping needed. You can parse an xlsx file to get these data.
If you're interested feel free to contribute to [rki-covid-parser](https://github.com/thebino/rki-covid-parser/issues/1)

**Comment by thebino** [comment]
Thanks @mampfes for adding the vaccination parsing to the [rki-covid-parser](https://pypi.org/project/rki-covid-parser/)

Since the vaccination data is only available on state level, it will probably take some changes. But I'll try to add it as soon as possible.

**Comment by mampfes** [comment]
The PR in rki-covid-parser just adds the raw vaccination numbers from impfdashboard.de. But actually, I also want to have the percentage rate available as sensor in Home Assistant. Calculating the numbers should be quite easy because the population seems to be available already.
Do you agree on this? If yes, would you add it to the rki-covid-parser or rki_covid? If rki-covid-parser, I can offer to create another PR.

**Comment by thebino** [comment]
I would suggest to add it to the HA integration since this numbers should be available via additional sensors.
Also HA will take car of persisting the history, so you can add a linear graph to lovelace to view the velocity of vaccinations.

I think we have to start with an ugly workaround in sensor.py:81
```
if district[CONF_DISTRICT_NAME].startswith("BL"):
    // add additional sensors
```
