### ISSUE TITLE
Wrong numbers for states 

### ISSUE THREAD

**Issue by mitch-thomas** [thebino/rki_covid#43]
The numbers for the state Niedersachsen are wrong/too high.
(e.g. sensor.bl_niedersachsen_count)

1. Install rki_covid sensor manually
2. Add integration in Home Assistant for any district (e.g. "LK Hildesheim")
3. Add integration in Home Assistant for any state (e.g. "BL Niedersachsen")
4. Watch "sensor.bl_niedersachsen_count" 

Analysis:
The sensor "sensor.bl_niedersachsen_count" shows twice the correct value (cases).
If another district is added, it will show three times the correct values.

Version:
Homeassistant: 2021.4.6
rki_covid: 1.5.2
rki-covid-parser: 1.2.0

**Comment by Vedeneb** [comment]
Same issue for Baden Württemberg.

If I fetch the API manually (e.g. https://api.corona-zahlen.org/states/BW) it shows correct values.

**Comment by thebino** [comment]
Data is provided by RKI and not by api.corona-zahlen.org
The data is identically to the numbers from the [official RKI Dashboard](https://experience.arcgis.com/experience/478220a4c454480e823b17327b2bf1d4/page/page_0/)

**Comment by Vedeneb** [comment]
No, for me the values are not identicall to those from the official Dashboard.

Here's what the sensor values are:
![image](https://user-images.githubusercontent.com/39202639/120936671-4f0fca00-c709-11eb-9377-399755a46008.png)

Versus the Dashboard for Baden Württemberg:
![image](https://user-images.githubusercontent.com/39202639/120936700-749cd380-c709-11eb-914c-d788af745bbd.png)


As you can see the sensor values are way off, only the 7 days incidence seems to be correct

**Comment by Vedeneb** [comment]
While looking at both screenshots I just realised the sensor values seem to be a triple of the actual value. E.g. death cases shows 30051 people while the official value is 10017

**Comment by Vedeneb** [comment]
Okay now it's getting weird, the sensor values just updated and now they display 4 times the original value:
![image](https://user-images.githubusercontent.com/39202639/120936829-4ec3fe80-c70a-11eb-87ca-7671a666563a.png)

This seems to happen multiple times:
![image](https://user-images.githubusercontent.com/39202639/120936877-8af75f00-c70a-11eb-8887-bc791c825e5c.png)

**Comment by thebino** [comment]
This is related to https://github.com/thebino/rki-covid-parser/issues/4 and will be fixed soon.
