### ISSUE TITLE
Wrong Values for BL Baden Württemberg

### ISSUE THREAD

**Issue by LuckyTriple7** [thebino/rki_covid#47]
**🐛 Describe the bug**

![image](https://user-images.githubusercontent.com/60685158/123913614-b45c8100-d97e-11eb-87d9-c5a86d5afa35.png)

The values are absolutely wrong, For a few weeks now.

![image](https://user-images.githubusercontent.com/60685158/123913811-eff74b00-d97e-11eb-8349-b472716d2c1d.png)

**💥 When did the bug occurred.***
- [ ] Installation / First-run
- [ ] Configuration
- [x] Other

**👣 To Reproduce**

**💻 Versions (please complete the following information):**

 - OS: [e.g. core-2021.6.6]

**Comment by LuckyTriple7** [comment]
Correct Values: Inzidenz: 6,53 / Gesamtfälle: 500.569

**Comment by LuckyTriple7** [comment]
Today, the values seems to be OK ...

![image](https://user-images.githubusercontent.com/60685158/124095998-79c81680-da5a-11eb-8e3a-1b0676576b61.png)

![image](https://user-images.githubusercontent.com/60685158/124096072-8b112300-da5a-11eb-8da4-9215c2283980.png)

**Comment by LuckyTriple7** [comment]
sorry, but the values are not OK !
Fälle Gesamt: 500.702 and not 1.001.404
I reloaded the Integration, now i see the following values:

![image](https://user-images.githubusercontent.com/60685158/124096650-1094d300-da5b-11eb-9c1e-90a5235b0fda.png)

**Comment by LuckyTriple7** [comment]
It seems like the number is always adding up.
**500702** 1001404, 1502106 ...

**Comment by thebino** [comment]
This is a duplicate of #43
