### ISSUE TITLE
Add support for HAs long term statistics capability please

### ISSUE THREAD

**Issue by Pe-MaKer** [thebino/rki_covid#52]
Thanks a lot for your great little integration. Now I don't have to scrape the regional data from the websites of the Landratsämter nearby anymore.  
Since Version 2021.8 Home Assistant is able to keep long term data of measuring entities as long as they are flagged as relevant for statistic purposes.
The entity has to have the `state_class: measurement`

See https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics for further details.
I hope you can implement this feature request without a lot of effort.

**Comment by Pe-MaKer** [comment]
Sorry for bringing this up again.
Sadly even after updating to HA 2021.9 the rki-sensor (v1.5.4) is still not listed as long term statistic source.

**Comment by thebino** [comment]
@Pe-MaKer can you please try to re-test it with the latest version. I added a missing property to fully support long-term statistics

**Comment by Pe-MaKer** [comment]
@thebino Sadly it doesn't work for me yet.
The Sensor itself is working but it isn't listed in the Statistics Graph Cards UI editor.
Does it work for you?
