### ISSUE TITLE
HACS Installation no longer working

### ISSUE THREAD

**Issue by jannis3005** [thebino/rki_covid#54]
**🐛 Describe the bug**

Since Update to 1.5.4 the Integration can no longer correctly be installed by HACS. I got notified about an update today and it wants to downgrade to 1.2.0, and the newest available version is 1.4.1
![image](https://user-images.githubusercontent.com/38779449/128827230-c3433664-d991-43f5-a195-a456a060c272.png)

**💥 When did the bug occurred.***
- [x] Installation / First-run
- [ ] Configuration
- [ ] Other

**👣 To Reproduce**

1. Go to 'HACS > Integrations > RKI Covid'
2. Click on 'Install this Repository in HACS'
4. See versions listed

**🧐 Expected behavior**

Except all Versions from Github to be available including previously available version 1.5.3 und new Version 1.5.4

**💻 Versions (please complete the following information):**

 - OS: Raspbian Buster 64bit with Homeassistant 2021.8.0 in Docker
 - Browser: Fails in all Browsers the same way

**🗄 Logfiles (Configuration > Logs)**

Could not find any error in log regarding installation and retreiving of versions

**Comment by UraniumDonut** [comment]
Issue has been reproduced on FreeBSD Truenas HACS Core installation.

**Comment by no0ner** [comment]
Same for me on Debian 10 Supervised.

core-2021.8.5
supervisor-2021.06.8

**Comment by thebino** [comment]
Sorry, updating old releases isn't a good Idea. HACS is not searching for the newest version, it is just using the last updated 🤦
