### ISSUE TITLE
Feature Request: hospitalization rate

### ISSUE THREAD

**Issue by Pe-MaKer** [thebino/rki_covid#56]
Thanks for this great custom component!
After all, as of yesterday, incidence is no longer the sole deciding factor for Corona countermeasures.
At least for Bavaria, the hospitalization rate will take its place as the "hospital traffic light".

It would be great if this component were supplemented by the hospitalization rate and the intensive care rate, which is provided here for all federal states: [https://www.intensivregister.de/#/aktuelle-lage/laendertabelle](https://www.intensivregister.de/#/aktuelle-lage/laendertabelle)
Maybe this repo is helpful in any way for scraping the data: [https://github.com/br-data/corona-divi-api](https://github.com/br-data/corona-divi-api)

With these two values, I can build my Corona Traffic Light within HA based on the regional principles:
red: >600 intensive care cases
yellow: >1.200 cases in hospitals
green: both values below their limit

**Comment by thebino** [comment]
Since these data is not provided by the RKI, a separate integration would be a better fit.
But contributions are always welcome, so feel free to add you local traffic light here. I'll try to support as much as possible.

**Comment by thebino** [comment]
There is an official [git repository](https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland/) providing the hospitalization data now.

**Comment by renarena** [comment]
I would like this too.

**Comment by thebino** [comment]
I already added the hospitalization numbers into the parser [with this PR](https://github.com/thebino/rki-covid-parser/pull/16).

**Comment by Pe-MaKer** [comment]
Great @thebino!
Thanks!
