### ISSUE TITLE
Ended support of baseurl not mentioned in README and CHANGELOG

### ISSUE THREAD

**Issue by marrobHD** [thebino/rki_covid#58]
**🐛 Describe the bug**

Ended support of baseurl not mentioned in README and CHANGELOG
https://github.com/thebino/rki_covid/blob/f6b97ebfde9d829ce47c90e7a9772bac8ed2fdb4/custom_components/rki_covid/sensor.py#L71

**💥 When did the bug occurred.***
- [ ] Installation / First-run
- [x] Configuration
- [ ] Other

**👣 To Reproduce**

1. Set baseurl to any url in sensor configuration
2. See error in logs

**🧐 Expected behavior**

Working baseurl feature

**Comment by thebino** [comment]
Since version 1.5.0 the component does not handle the parsing itself.
Parsing is done by [rki-covid-parser](https://github.com/thebino/rki-covid-parser/) which reads data directly from the rki without any 3rd party services.
Sorry for the inconvenience.
