### ISSUE TITLE
Feature Request: Add Active cases sensor

### ISSUE THREAD

**Issue by thesmer** [thebino/rki_covid#6]
Hi, 
I like your integration very much. would it be possible to add the active cases per "Landkreis". 

Thanks a lot for any response.

**Comment by thebino** [comment]
There is only data provided by RKI for the summary count which can be found as entity as well.

**Comment by thesmer** [comment]
I see, thought the numbers of our local dashboard would be provided as well:
https://lrabb.maps.arcgis.com/apps/opsdashboard/index.html#/894cf4513aa1402f8f9944f22dfc3b68

any chance/tipp to me to querry those? 

and as reference: your numbers work nicely in my dashboard:
![image](https://user-images.githubusercontent.com/16209162/103352567-d2682800-4aa6-11eb-92cf-daa0fb83fa21.png)

**Comment by thebino** [comment]
It doesn’t look like, the website/dashboard you mentioned is offering any API to request the numbers.

I’m also really certain, the numbers aren’t right.

8658 Fälle im LK - 8193 genesene - 122 Todesfälle = 343 Aktive Fälle

1) you can’t measure, when a person is “healed"
2) people can become infected multiple times in rare cases

So what exactly is the “active cases” measuring? Are these people in a hospital, on intensive care or only quarantined?

The data are wrapped by this api and the rki don’t seem to provide these details but feel free to check the source by yourself:
https://github.com/marlon360/rki-covid-api/blob/master/server/cronjobs/updateDistricts.js#L10

**Comment by gebripe** [comment]
If that helps, there's a full-blown data service w/ API at
https://npgeo-corona-npgeo-de.hub.arcgis.com/search?collection=Dataset
also broken down into federal states and districts, e.g.
https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/ef4b445a53c1406892257fe63129a8ea_0
https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/917fc37a709542548cc3be077a786c17_0

**Comment by thebino** [comment]
Thanks @gebripe 
The api used by this implementation is wrapping arcgis.com datasets as well 👍
