### ISSUE TITLE
integration deprecated under HA OS 6.4

### ISSUE THREAD

**Issue by stm2roi3** [thebino/rki_covid#61]
**🐛 Describe the bug**

**💥 When did the bug occurred.***
- After system update

**👣 To Reproduce**

1. Update core to core version  2021.9.7
2. Update supervisor to supervisor-2021.09.6
3. Update OS to Home Assistant OS 6.4
3. Go to configuration > integrations > rki covid numbers
4. See error, also lovelace dashboard shows entities as "not available"

**🗄 Logfiles (Configuration > Logs)**

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:268
Integration: Sensor (documentation, issues)
First occurred: 23:19:51 (3 occurrences)
Last logged: 23:19:51
Platform rki_covid not ready yet: Data coordinator could not be initialized!; Retrying in background in 30 seconds

--------------------------------

Logger: custom_components.rki_covid
Source: custom_components/rki_covid/__init__.py:78
Integration: RKI Covid numbers (documentation, issues)
First occurred: 23:19:50 (1 occurrences)
Last logged: 23:19:50
Unexpected error fetching rki_covid data: unsupported operand type(s) for +=: 'int' and 'NoneType'

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/rki_covid/__init__.py", line 78, in async_get_districts
    await parser.load_data()
  File "/usr/local/lib/python3.9/site-packages/rki_covid_parser/parser.py", line 26, in load_data
    await self._merge_states()
  File "/usr/local/lib/python3.9/site-packages/rki_covid_parser/parser.py", line 132, in _merge_states
    self.states[district.state].recovered += district.recovered
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType

**Comment by sevorl** [comment]
I can confirm this is broken

**Comment by thebino** [comment]
Should be fixed with the [latest version 1.5.6](https://github.com/thebino/rki_covid/releases/tag/1.5.6) of this rki_covid integration.

**Comment by damanti-me** [comment]
Nice, thank you! Danke!
