### ISSUE TITLE
HA warning: Icon mdi:christianity was renamed to mdi:cross

### ISSUE THREAD

**Issue by uherting** [thebino/rki_covid#65]
**🐛 Describe the bug**

In the HA log file a message is to be found:
"frontend.js.latest.202111030] Icon mdi:christianity was renamed to mdi:cross, please change your config, it will be removed in version 2021.12"

**💥 When did the bug occurred.***
- [ ] Installation / First-run
- [ ] Configuration
- [ X] Other

**👣 To Reproduce**

1. Go to: a page within the HA instance where the RKI sensors are displayed.
4. See error in the logfile home-assistant.log

**🧐 Expected behavior**

This message should not pop up in the log file

**💻 Versions (please complete the following information):**
System Health

version: core-2021.11.1
installation_type: Home Assistant Supervised
dev: false
hassio: true
docker: true
user: root
virtualenv: false
python_version: 3.9.7
os_name: Linux
os_version: 5.10.0-9-amd64
arch: x86_64
timezone: Europe/Berlin

GitHub API: ok
Github API Calls Remaining: 4076
Installed Version: 1.16.0
Stage: running
Available Repositories: 895
Installed Repositories: 75

can_reach_server: ok
remaining_requests: 47

logged_in: false
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: ok

host_os: Debian GNU/Linux 11 (bullseye)
update_channel: stable
supervisor_version: supervisor-2021.10.8
docker_version: 20.10.10
disk_total: 115.9 GB
disk_used: 22.2 GB
healthy: true
supported: true
supervisor_api: ok
version_api: ok
installed_addons: ESPHome (2021.10.3), Home Assistant Google Drive Backup (0.105.2), Visual Studio Code (3.6.2), MariaDB (2.4.0), Terminal & SSH (9.2.1), Node-RED (10.0.1), Mosquitto broker (6.0.1), Tor (3.0.5)

dashboards: 5
resources: 6
views: 26
mode: yaml

 - OS: Debian GNU/Linux 11 (bullseye)
 - HA: core-2021.11.1
 - Supervisor: supervisor-2021.10.8
 - Browser  firefox v94.0 (64-bit) on Ubuntu 20.04.3 LTS 
 - **🗄 Logfiles (Configuration > Logs)**
"frontend.js.latest.202111030] Icon mdi:christianity was renamed to mdi:cross, please change your config, it will be removed in version 2021.12"

> 🎓 Increase the log level for this custom integration by adding the following lines to the `configuration.yaml`
```
logger:
  default: info
  logs:
    custom_components.rki_covid.sensor: debug
```
Add regarding log messages from the Logs for more details.

**Comment by thebino** [comment]
Thanks for bringing this up, it was already solved by #63 and will be released in the next version.
