### ISSUE TITLE
HA2021.12: Log warning: device_state_attributes depreciated

### ISSUE THREAD

**Issue by KNXBroker** [thebino/rki_covid#68]
**🐛 Describe the bug**

There is a new warning in the logger:
Integration implement device_state_attributes. Please report it to the custom component author.
Seems that device_state_attributes is going to be depreciated.

**💥 When did the bug occurred.***
- [ ] Installation / First-run
- [ ] Configuration
- [X] Other

**👣 To Reproduce**

1. Install HA 2021.12.0b0
2. Go to 'Logs'
3. See error

**🧐 Expected behavior**

No Warning

**💻 Versions (please complete the following information):**

 - OS: core-2021.12.0b0

**🗄 Logfiles (Configuration > Logs)**

> 🎓 Increase the log level for this custom integration by adding the following lines to the `configuration.yaml`
```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:543
First occurred: 4. Dezember 2021, 20:12:35 (3773 occurrences)
Last logged: 06:37:36

Entity sensor.deutschland_casesper100k (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.deutschland_newcases (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
```
Add regarding log messages from the Logs for more details.

**Comment by thebino** [comment]
This will be resolved in the next version. Which will probably been shipped with Home-Assistant itself.
