### ISSUE TITLE
RKI covid numbers are not updated

### ISSUE THREAD

**Issue by seiferrtalle** [thebino/rki_covid#69]
Hello,

is it only me who has the problem that the RKI covid numbers are not updated? Or is this a general problem? Has RKI changed something?
Until about shortly before Christmas everything ran fine, I have not changed anything in the configuration since then. However, the data is not being updated. Sensors are available.

![grafik](https://user-images.githubusercontent.com/68616885/147651530-fbfc7a96-0bdf-4cfe-b749-35b66e691d59.png)

HASS
Version core-2021.12.5
Installation type Home Assistant OS
Development false
Supervisor true
Docker true
User root
Virtual environment false
Python version 3.9.7
Operating system family Linux
Operating system version 5.10.63-v7l
CPU architecture armv7l
Time zone Europe/Berlin

Host operating system Home Assistant OS 7.0
Update channel stable
Supervisor version supervisor-2021.12.2
Docker version 20.10.9
Total disk space 109.3 GB
Disk space used 32.8 GB
Healthy true
Supported true
Board rpi4
Supervisor API ok
Version API ok

Thanx and BR,
Ralf

**Comment by LuckyTriple7** [comment]
It happens to me every couple of weeks. Do not know why.
Delete All RKI Integrations
![image](https://user-images.githubusercontent.com/60685158/147654840-ab3b4fbb-c387-4ba2-bdc9-0d4923b858f5.png)
Restart HA and than add it again.

**Comment by seiferrtalle** [comment]
@LuckyTriple7

thank you for the quick reply! 👍‍

**Comment by thebino** [comment]
@seiferrtalle Could you add logfile so I can have a closer look on this issue. Haven't seen it myself yet.
Anyway the integration [will be part of Home-Assistant soon](https://github.com/home-assistant/core/pull/60506). So we can ensure, it has nothing to do with HACS.

**Comment by seiferrtalle** [comment]
@thebino below are the log entries since the last restart on 2021-12-25.

I'll do a restart again in a minute and see what he speaks to us then .... 😉

	Zeile 3: 2021-12-25 13:41:44 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration rki_covid which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
	Zeile 25: 2021-12-25 13:42:29 WARNING (MainThread) [homeassistant.setup] Setup of rki_covid is taking over 10 seconds.
	Zeile 132: 2021-12-25 13:42:56 ERROR (MainThread) [custom_components.rki_covid] Error fetching rki_covid data: Error reading data from rki-covid-parser timed-out: 
	Zeile 132: 2021-12-25 13:42:56 ERROR (MainThread) [custom_components.rki_covid] Error fetching rki_covid data: Error reading data from rki-covid-parser timed-out: 
	Zeile 132: 2021-12-25 13:42:56 ERROR (MainThread) [custom_components.rki_covid] Error fetching rki_covid data: Error reading data from rki-covid-parser timed-out: 
	Zeile 231: 2021-12-25 13:43:32 WARNING (MainThread) [homeassistant.components.sensor] Platform rki_covid not ready yet: Data coordinator could not be initialized!; Retrying in background in 30 seconds
	Zeile 232: 2021-12-25 13:43:32 WARNING (MainThread) [homeassistant.components.sensor] Platform rki_covid not ready yet: Data coordinator could not be initialized!; Retrying in background in 30 seconds
	Zeile 233: 2021-12-25 13:43:32 WARNING (MainThread) [homeassistant.components.sensor] Platform rki_covid not ready yet: Data coordinator could not be initialized!; Retrying in background in 30 seconds
	Zeile 234: 2021-12-25 13:43:32 WARNING (MainThread) [homeassistant.components.sensor] Platform rki_covid not ready yet: Data coordinator could not be initialized!; Retrying in background in 30 seconds
	Zeile 235: 2021-12-25 13:43:32 WARNING (MainThread) [homeassistant.components.sensor] Platform rki_covid not ready yet: Data coordinator could not be initialized!; Retrying in background in 30 seconds
	Zeile 6315: 2021-12-25 13:49:40 WARNING (MainThread) [homeassistant.core] Something is blocking Home Assistant from wrapping up the start up phase. We're going to continue anyway. Please report the following info at https://github.com/home-assistant/core/issues: fritzbox_callmonitor, switch, rest_command, sensor.hacs, daikin, notify.mobile_app, sensor.miflora, meross_cloud, config, energy, weather.met, media_player, network, light.fritzbox, default_config, number, device_tracker.bluetooth_tracker, sensor.pi_hole, updater, kia_uvo, yamaha_musiccast, auth, dlna_dmr, tado, cover, sensor.anniversary, homeassistant, light, sensor.dwd_weather_warnings, notify, binary_sensor.zha, binary_sensor.pi_hole, homematicip_cloud, sensor.mobile_app, input_boolean, binary_sensor.kia_uvo, usb, timer, calendar.google, sensor.broadlink, cover.tradfri, cover.zha, sensor.energy, sensor.systemmonitor, sensor.home_connect, tts, binary_sensor.shelly, switch.somfy, switch.meross_cloud, analytics, rpi_power, input_text, switch.wake_on_lan, light.home_connect, system_log, webhook, map, device_tracker, history, lock.kia_uvo, switch.switchbot, sensor.waste_collection_schedule, switch.broadlink, sensor.mitemp_bt, sensor.shelly, waste_collection_schedule, sensor.tado, api, recorder, light.tplink, media_player.cast, http, home_connect, input_number, binary_sensor.rpi_power, sensor.zha, netatmo, sensor.tradfri, sensor.rest, lovelace, blueprint, cast, harmony, media_player.spotify, lock.zha, dhcp, water_heater.tado, select, sensor.moon, wake_on_lan, somfy, device_automation, switch.tplink, template, counter, sun, met, siren, binary_sensor.updater, script, sensor.somfy, binary_sensor.home_connect, tplink, camera.generic, my, device_tracker.zha, camera, climate, person, lock, climate.somfy, notify.pushover, fan, tag, tankerkoenig, group, binary_sensor, scene.homeassistant, calendar.waste_collection_schedule, search, sensor.fritzbox_callmonitor, cover.meross_cloud, climate.meross_cloud, number.zha, frontend, water_heater, sensor.time_date, lig ...
	Zeile 147934: 2021-12-29 11:04:50 WARNING (SyncWorker_9) [homeassistant.loader] We found a custom integration rki_covid which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
	Zeile 149026: 2021-12-29 11:46:17 WARNING (MainThread) [homeassistant.components.sensor] Platform rki_covid not ready yet: Data coordinator could not be initialized!; Retrying in background in 30 seconds

**Comment by seiferrtalle** [comment]
@thebino and here some new log entries after a fresh restart, hope that helps?

	Zeile 4: 2021-12-29 13:28:27 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration rki_covid which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
	Zeile 143: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.bl_bayern_deaths (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 143: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.bl_bayern_deaths (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 144: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.bl_bayern_recovered (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 144: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.bl_bayern_recovered (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 145: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.bl_bayern_weekincidence (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 145: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.bl_bayern_weekincidence (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 146: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.bl_bayern_casesper100k (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 146: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.bl_bayern_casesper100k (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 147: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.bl_bayern_newcases (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 147: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.bl_bayern_newcases (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 148: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.bl_bayern_newdeaths (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 148: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.bl_bayern_newdeaths (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 149: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.bl_bayern_newrecovered (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 149: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.bl_bayern_newrecovered (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 150: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.lk_schweinfurt_count (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 150: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.lk_schweinfurt_count (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 151: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.lk_schweinfurt_deaths (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 151: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.lk_schweinfurt_deaths (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 152: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.lk_schweinfurt_recovered (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 152: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.lk_schweinfurt_recovered (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 153: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.lk_schweinfurt_weekincidence (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 153: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.lk_schweinfurt_weekincidence (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 154: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.lk_schweinfurt_casesper100k (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 154: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.lk_schweinfurt_casesper100k (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 155: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.lk_schweinfurt_newcases (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 155: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.lk_schweinfurt_newcases (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 156: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.lk_schweinfurt_newdeaths (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 156: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.lk_schweinfurt_newdeaths (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 157: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.lk_schweinfurt_newrecovered (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 157: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.lk_schweinfurt_newrecovered (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 158: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.sk_schweinfurt_count (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 158: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.sk_schweinfurt_count (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 159: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.sk_schweinfurt_deaths (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 159: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.sk_schweinfurt_deaths (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 160: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.sk_schweinfurt_recovered (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 160: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.sk_schweinfurt_recovered (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 161: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.sk_schweinfurt_weekincidence (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 161: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.sk_schweinfurt_weekincidence (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 162: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.sk_schweinfurt_casesper100k (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 162: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.sk_schweinfurt_casesper100k (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 163: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.sk_schweinfurt_newcases (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 163: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.sk_schweinfurt_newcases (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 164: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.sk_schweinfurt_newdeaths (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 164: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.sk_schweinfurt_newdeaths (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 165: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.sk_schweinfurt_newrecovered (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 165: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.sk_schweinfurt_newrecovered (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 166: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.lk_wurzburg_count (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 166: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.lk_wurzburg_count (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 167: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.lk_wurzburg_deaths (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 167: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.lk_wurzburg_deaths (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 168: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.lk_wurzburg_recovered (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 168: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.lk_wurzburg_recovered (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 169: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.lk_wurzburg_weekincidence (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 169: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.lk_wurzburg_weekincidence (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 170: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.lk_wurzburg_casesper100k (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 170: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.lk_wurzburg_casesper100k (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 171: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.lk_wurzburg_newcases (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 171: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.lk_wurzburg_newcases (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 172: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.lk_wurzburg_newdeaths (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 172: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.lk_wurzburg_newdeaths (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 173: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.lk_wurzburg_newrecovered (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 173: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.lk_wurzburg_newrecovered (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 174: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.sk_wurzburg_count (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 174: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.sk_wurzburg_count (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 175: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.sk_wurzburg_deaths (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 175: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.sk_wurzburg_deaths (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 176: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.sk_wurzburg_recovered (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 176: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.sk_wurzburg_recovered (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 177: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.sk_wurzburg_weekincidence (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 177: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.sk_wurzburg_weekincidence (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 178: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.sk_wurzburg_casesper100k (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 178: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.sk_wurzburg_casesper100k (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 179: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.sk_wurzburg_newcases (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 179: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.sk_wurzburg_newcases (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 180: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.sk_wurzburg_newdeaths (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 180: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.sk_wurzburg_newdeaths (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 181: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.sk_wurzburg_newrecovered (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 181: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.sk_wurzburg_newrecovered (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 202: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform rki_covid is taking over 10 seconds.
	Zeile 203: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform rki_covid is taking over 10 seconds.
	Zeile 204: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform rki_covid is taking over 10 seconds.
	Zeile 205: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform rki_covid is taking over 10 seconds.
	Zeile 206: 2021-12-29 13:29:54 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform rki_covid is taking over 10 seconds.
	Zeile 259: 2021-12-29 13:30:13 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.bl_bayern_count (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
	Zeile 259: 2021-12-29 13:30:13 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.bl_bayern_count (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by seiferrtalle** [comment]
Fascinating! I did nothing - except the last restart on 13:29 - and now the values were updated - without further action from my side! 🙃

**Comment by thebino** [comment]
Looks like the rki-parser got no response from the rki servers within 10 seconds. As you can see in the logs home-assisstant will retry it in background. Perhaps the rki servers where busy.

**Comment by GerdRuetten** [comment]
I also have the problem that the parser does not update 

After a System-Restart i see in the logfile:

2022-02-08 04:05:01 ERROR (MainThread) [custom_components.rki_covid] Error fetching rki_covid data: Error reading data from rki-covid-parser timed-out:

Thats all.
No more Log-Entries with rki_covid.

It seems, the component does't restart himself if the RKI-Api not reach ... possible?
