### ISSUE TITLE
Temporary loss of data

### ISSUE THREAD

**Issue by felix-schreib** [thebino/rki_covid#7]
Hi,
I like your integration.

I have trouble with a temporary loss of data. It occures at the same time for all sensors for all my monitored districts.

The screenshot below shows the history of the last roughly 48hrs.
![Screenshot 2021-01-06 143933](https://user-images.githubusercontent.com/47690527/103788646-61dd8000-503f-11eb-82ac-5b21cbfcaf70.png)

My Homeassistant worked flawless overwise in the timeperiods of data loss.

**Comment by thebino** [comment]
Yes, it looks like the API behind couldn't be reached. Try to reload the integration via `Configuration > Integration > reload`

```
Logger: custom_components.rki_covid
Source: helpers/update_coordinator.py:166
Integration: RKI Covid numbers (documentation, issues)
First occurred: 12:04:25 AM (2 occurrences)
Last logged: 3:04:35 PM
Error fetching rki_covid data: 
```

**Comment by felix-schreib** [comment]
OK, thanks. I will try this the next time I lose data. I guess there is nothing to do since the RKI API isn't reachable.
