### ISSUE TITLE
Warning "device_state_attributes" at startup

### ISSUE THREAD

**Issue by Gloomyeye** [thebino/rki_covid#70]
**🐛 Describe the bug**

I got the following warning at startup of home assistant.

**💥 When did the bug occurred.***
- [] Installation / First-run
- [ ] Configuration
- [X] Other: Startup of Home Assistant

**👣 To Reproduce**

Starting of home assistant

**🧐 Expected behavior**

No warning occurs ;-)

**💻 Versions (please complete the following information):**

 - Docker: home assistant 2021.12.8
 - Browser: Firefox

**🗄 Logfiles (Configuration > Logs)**

> 🎓 Increase the log level for this custom integration by adding the following lines to the `configuration.yaml`
```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
First occurred: 16:15:16 (14 occurrences)
Last logged: 16:15:35

Entity sensor.glo_covid_bl_niedersachsen_count (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.glo_covid_bl_niedersachsen_weekincidence (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.glo_covid_bl_niedersachsen_casesper100k (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.glo_covid_bl_niedersachsen_newcases (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.glo_covid_lk_oldenburg_count (<class 'custom_components.rki_covid.sensor.RKICovidNumbersSensor'>) implements device_state_attributes. Please report it to the custom component author.
```
Add regarding log messages from the Logs for more details.

**Comment by LuckyTriple7** [comment]
not included in Beta 2022.2. So please fix that issue here, thx alot.

**Comment by Florian-Schmidt** [comment]
Just found the same logs… Google found showed solution mentioned above by renaming for me. 

Perhaps, there could be an update instead of waiting for HA integration or closing this issue also.

**Comment by Florian-Schmidt** [comment]
Renaming inside sensor.py seems to solve this issue.

**Comment by niklas1375** [comment]
@Florian-Schmidt thanks! That did indeed resolve (or at least hide) the issue for me :)

**Comment by thebino** [comment]
Please try again with the latest version [1.5.7](https://github.com/thebino/rki_covid/releases/tag/1.5.7)
