### ISSUE TITLE
Parser timed out

### ISSUE THREAD

**Issue by umrath** [thebino/rki_covid#73]
**🐛 Describe the bug**

Today's Covid numbers have not been generated

**💥 When did the bug occurred.***
- [ ] Installation / First-run
- [ ] Configuration
- [X] Other

**👣 To Reproduce**

Unsure as the it runs automatically in the background.

**🧐 Expected behavior**

I expected the current Covid numbers to be issued.

**💻 Versions (please complete the following information):**

 - OS: core-2022.2.3
 - Supervisor: supervisor-2022.01.1
 - Browser: Any

**🗄 Logfiles (Configuration > Logs)**

Increasing the log level will not help much as the run for today has happened already.

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.rki_covid
Source: helpers/update_coordinator.py:219
Integration: RKI Covid numbers (documentation, issues)
First occurred: 07:12:23 (1 occurrences)
Last logged: 07:12:23

Error fetching rki_covid data: Error reading data from rki-covid-parser timed-out:

[seems there was not more log data]

**Comment by LuckyTriple7** [comment]
I get this error every few days.
Soluton: Delete ALL RKI Covid Integrations in HA, Restart HA, Add Integration(s) again

**Comment by umrath** [comment]
> I get this error every few days. Soluton: Delete ALL RKI Covid Integrations in HA, Restart HA, Add Integration(s) again

This does not sound like a solution but rather like a workaround to me.
Meanwhile it fixed itself again.

So, maybe really just timeout on the RKI side. A bit more information regarding what exactly caused the timeout would be helpful.

**Comment by umrath** [comment]
Guess it's not relevant enough to chase. Seems to fix itself eventually.

**Comment by LuckyTriple7** [comment]
> > I get this error every few days. Soluton: Delete ALL RKI Covid Integrations in HA, Restart HA, Add Integration(s) again
> 
> This does not sound like a solution but rather like a workaround to me. Meanwhile it fixed itself again.
> 
> So, maybe really just timeout on the RKI side. A bit more information regarding what exactly caused the timeout would be helpful.

I don't think it's a timeout.
You  can wait many hours, dont fix. You can restart HA, dont fix.
Deleting Integrations, restart HA and add again is the solution.
There were already a lot of tickets for this, but nobody cares.
