### ISSUE TITLE
Newcases and Newdeaths always show 0

### ISSUE THREAD

**Issue by GerdRuetten** [thebino/rki_covid#79]
Dear Benjamin,

in the last few days, the two entities newcases and newdeaths always show only 0 for four different locations (BL Nordrhein-Westfalen, Deutschland, LK Rhein-Erft-Kreis, SK Köln).

The other entities show the current values.

Has the RKI perhaps changed something or where could the error come from?

I use version 1.5.7 installed via HACS

**Comment by thebino** [comment]
Will be handled by the [parser over here](https://github.com/thebino/rki-covid-parser/issues/21)
