### ISSUE TITLE
FR: Localization the Unit of measurement

### ISSUE THREAD

**Issue by GerdRuetten** [thebino/rki_covid#82]
Hi,

a feature request for the HACS- or/and Native-Version of this integration:

The unit_of_measurement are hardcoded in the sensor.py:

```
    def unit_of_measurement(self):
        """Return unit of measurement."""
        if (
            self.info_type == "count"
            or self.info_type == "deaths"
            or self.info_type == "recovered"
        ):
            return "people"
        elif self.info_type == "weekIncidence":
            return "nb"
        else:
            return "cases"

```
For a better user experience, the units should be able to be localized.

Best regards

Gerd

**Comment by thebino** [comment]
Haven't seen localization inside sensors. If I missed it, reopen the issue and point me the direction.

**Comment by GerdRuetten** [comment]
> Haven't seen localization inside sensors. If I missed it, reopen the issue and point me the direction.

I post it before :-)

sensor.py, line 170ff

    @property
    def unit_of_measurement(self):
        """Return unit of measurement."""
        if (
            self.info_type == "count"
            or self.info_type == "deaths"
            or self.info_type == "recovered"
        ):
            return "people"
        elif self.info_type == "weekIncidence":
            return "nb"
        else:
            return "cases"

**Comment by thebino** [comment]
This is just a copy of my code, but no solution how to achieve a localization based on the user settings.
