### ISSUE TITLE
cannot import name 'RkiCovidParser' from 'rki_covid_parser.parser'

### ISSUE THREAD

**Issue by Rothammel** [thebino/rki_covid#83]
**🐛 Describe the bug**

**💥 When did the bug occurred.***
- [ ] Installation / First-run
- [ ] Configuration
- [x] Other

**👣 To Reproduce**

Logger: homeassistant.setup
Source: setup.py:155
First occurred: 20:29:20 (1 occurrences)
Last logged: 20:29:20

Setup failed for rki_covid: Unable to import component: cannot import name 'RkiCovidParser' from 'rki_covid_parser.parser' (/usr/local/lib/python3.9/site-packages/rki_covid_parser/parser.py)

**💻 Versions (please complete the following information):**

 - OS: core-2022.3.0
 - Supervisor: supervisor-2022.01.1
 - Browser chrome version 98.0.4758.102 (Offizieller Build) (64-Bit)

**Comment by thebino** [comment]
dependencies are handled by home assistant, looks like something is wrong with the setup or the [python package indexer](https://pypi.org/) was not reachable at a time. There is nothing I can do to fix this.

Try to restart your HA or raise an issue at HA

**Comment by Rothammel** [comment]
today there was a home assistant core update, now everything works. Thank you for your help
