### ISSUE TITLE
R-Value and Hospitalisation

### ISSUE THREAD

**Issue by DSDV** [thebino/rki_covid#87]
Hi, 
i found your great integration due to the link on: 
https://github.com/marlon360/rki-covid-api

there seems to be an integration for R-Value and Hospitalization. 

Would it be possible to add those two entity's?

with kind regards <3

**Comment by thebino** [comment]
There is already a draft to integrate this integration into the core home-assistant here: https://github.com/home-assistant/core/pull/66431

Right now I don't have any plans to move the changes over here. But feel free to contribute

**Comment by DSDV** [comment]
Oh cool :D 
so i dont misunderstand. When this draft will pass there will be all RKI Values (including R and Hospitalization) in the official HA-core?

**Comment by thebino** [comment]
No, only Hospitalization is implemented.
