### ISSUE TITLE
no sensors anymore - AttributeError: 'NoneType' object has no attribute 'fget'

### ISSUE THREAD

**Issue by bernd780** [thebino/rki_covid#88]
**** The module doesn't show any sensors anymore

**💥 When did the bug occurred.***
Reinstalled the module from HACS and same error - no sensors for any region

**👣 To Reproduce**

Install via HACS and add a region --> no sensors shown

**🧐 Expected behavior**

Install via HACS and add a region, sensors shown and values given.

**💻 Versions (please complete the following information):**

 Home Assistant 2023.8.4 Supervisor 2023.08.1 Operating System 10.5 Frontend 20230802.1 - latest 

**🗄 Logfiles (Configuration > Logs)**
LOG-Entry:
Logger: homeassistant.components.sensor
Source: helpers/entity.py:463
Integration: Sensor (documentation, issues)
First occurred: 13:19:24 (4 occurrences)
Last logged: 13:19:56

Error adding entities for domain sensor with platform rki_covid
Error while setting up rki_covid platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 643, in _async_add_entity
    suggested_object_id = entity.suggested_object_id
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 463, in suggested_object_id
    if self.__class__.name.fget is Entity.name.fget and self.platform:  # type: ignore[attr-defined]
       ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'fget'

> 🎓 Increase the log level for this custom integration by adding the following lines to the `configuration.yaml`
```
logger:
  default: info
  logs:
    custom_components.rki_covid.sensor: debug
```
Add regarding log messages from the Logs for more details.

**Comment by thebino** [comment]
The component will not be maintained anymore, feel free to get in contact if you are interested to take it over.

Sorry for such sad news.

**Comment by bernd780** [comment]
Thanks for the module, helped a lot in the past.
